server:
  port: 8080 #서버 포트지정

spring:
  profiles:
    include:
      - core #core module yml 포함
    active: local #진행할 active profiles

#SrpingDoc 설정 API 문서화
springdoc:
  version: 0.0.1
  api-docs:
    path: /api-docs
  #Media Type 기본 값을 application/json
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  swagger-ui:
    #api 및 태그 정렬 기준을 알파벳 오름차순
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    #swagger-ui default url인 petstore html 문서 비활성화 여부
    disable-swagger-default-url: true
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
  #OpenAPI 3 로 문서화할 api path 리스트
  paths-to-match:
    - /v1/**

---
spring:
  config:
    activate:
      on-profile: local